apiVersion: v1
kind: ConfigMap
metadata:
  name: pubmed-sync-scripts
  namespace: asgard-services
  labels:
    app.kubernetes.io/part-of: mimir
    app.kubernetes.io/component: data-source-sync
data: {}
