#!/usr/bin/env python3
"""
mock_flash_moe.py - Simulates the Flash-MoE OpenAI-compatible API
Run this to test Mimir's Flash-MoE architecture integration without downloading the 209GB weights.
"""
from http.server import BaseHTTPRequestHandler, HTTPServer
import json
import time

class MockFlashMoeHandler(BaseHTTPRequestHandler):
    def do_POST(self):
        if self.path.endswith('/v1/chat/completions'):
            content_length = int(self.headers['Content-Length'])
            post_data = self.rfile.read(content_length)
            req = json.loads(post_data.decode('utf-8'))
            
            # Extract last message
            messages = req.get('messages', [])
            last_message = messages[-1]['content'] if messages else ""

            print(f"[Flash-MoE Mock] Received prompt: {last_message[:50]}...")

            response = {
                "id": "chatcmpl-mock-flash-moe",
                "object": "chat.completion",
                "created": int(time.time()),
                "model": req.get("model", "Qwen3.5-397B-MoE"),
                "choices": [{
                    "index": 0,
                    "message": {
                        "role": "assistant",
                        "content": f"[Generated by Mock Flash-MoE Engine running on Port 8081]\n\nI am the simulated Qwen 397B engine! I received your prompt: '{last_message}'\n\nThe Asgard Mimir integration is working perfectly!"
                    },
                    "finish_reason": "stop"
                }],
                "usage": {
                    "prompt_tokens": len(last_message.split()),
                    "completion_tokens": 40,
                    "total_tokens": len(last_message.split()) + 40
                }
            }

            self.send_response(200)
            self.send_header('Content-type', 'application/json')
            self.end_headers()
            self.wfile.write(json.dumps(response).encode('utf-8'))
        else:
            self.send_response(404)
            self.end_headers()

def run(port=8081):
    server_address = ('', port)
    httpd = HTTPServer(server_address, MockFlashMoeHandler)
    print(f"🚀 Mock Flash-MoE Server running on port {port}...")
    try:
        httpd.serve_forever()
    except KeyboardInterrupt:
        pass
    httpd.server_close()
    print("Server stopped.")

if __name__ == '__main__':
    run()
